name: testnet-deploy

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: yarn
      - run: yarn build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.DEV_GYM_S3_BUCKET }}
          source_dir: "build"
          destination_dir: "./"
#       Invalidate Cloudfront (this action)
#       - name: invalidate
#         uses: chetan/invalidate-cloudfront-action@v2
#         env:
#           DISTRIBUTION: ${{ secrets.DISTRIBUTION_DEV_GYM }}
#           PATHS: "/*"
#           AWS_REGION: "us-east-1"
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
